full_name: Sven Fillinger
email: sven.fillinger@qbic.uni-tuebingen.de
project_name: omero-portlet
project_short_description: Omero-portlet. A imaging visualisation portlet for qPortal.
version: 1.3.0
domain: portlet
language: groovy
project_slug: omero-portlet
project_slug_no_hyphen: omero_portlet
template_version: '1.0.2 # <<QUBE_NO_BUMP>>'
template_handle: portlet-groovy
github_username: qbicsoftware
creator_github_username: luiskuhn
is_github_repo: false
is_repo_private: false
is_github_orga: false
copyright_holder: Luis Kuhn
license: MIT
main_class_prefix: Qbic
use_openbis_client: yes
use_openbis_raw_api: no
use_qbic_databases: no
use_vaadin_charts: no
