# This workflow will build a package using Maven and then publish it to
# qbic-repo.qbic.uni-tuebingen.de packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Nexus Package

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  publish_snapshots:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.9
        uses: actions/setup-java@v1
        with:
          java-version: 1.9
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }}

      - name: Load local Maven repository cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Remove existing snapshot tags which are not supposed to be present
      - name: Remove snapshot tags
        run: mvn versions:set -DremoveSnapshot
      # Set the SNAPSHOT for this build and deployment
      - name: Set version in Maven project
        run:  mvn versions:set -DnewVersion='${project.version}-SNAPSHOT'

      - name: Build compiled bundle with Maven
        run: mvn clean -B package --file pom.xml

      - name: Publish compiled bundle to QBiC Nexus Repository
        run: mvn --settings $GITHUB_WORKSPACE/.github.settings.xml deploy
        env:
          MAVEN_REPO_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_REPO_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
